# Generated by Django 5.1 on 2024-10-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0004_chat_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["time_create"],
                "verbose_name": "Повідомлення",
                "verbose_name_plural": "Повідомлення",
            },
        ),
        migrations.AlterField(
            model_name="chat",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
