# Generated by Django 5.1 on 2024-09-23 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_comment_text_alter_post_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(5000),
                ],
                verbose_name="Текст",
            ),
        ),
    ]
